/* eslint-disable import/no-cycle */
/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/*----------------------------- CALENDAR -----------------------------*/

// Get Calendar
export const DASHBOARD_GET_CALENDAR_LIST = 'DASHBOARD_GET_CALENDAR_LIST';
export const DASHBOARD_GET_CALENDAR_LIST_SUCCESS =
  'DASHBOARD_GET_CALENDAR_LIST_SUCCESS';
export const DASHBOARD_GET_CALENDAR_LIST_ERROR =
  'DASHBOARD_GET_CALENDAR_LIST_ERROR';

/*----------------------------- SPACE -----------------------------*/

// ------- LOCATION -----
// GET
export const SPACE_GET_LOCATION_LIST = 'SPACE_GET_LOCATION_LIST';
export const SPACE_GET_LOCATION_LIST_SUCCESS =
  'SPACE_GET_LOCATION_LIST_SUCCESS';
export const SPACE_GET_LOCATION_LIST_ERROR = 'SPACE_GET_LOCATION_LIST_ERROR';

// ADD
export const SPACE_ADD_LOCATION = 'SPACE_ADD_LOCATION';
export const SPACE_ADD_LOCATION_SUCCESS = 'SPACE_ADD_LOCATION_SUCCESS';
export const SPACE_ADD_LOCATION_ERROR = 'SPACE_ADD_LOCATION_ERROR';

// ------- FLOOR -----
// ADD
export const SPACE_ADD_LOCATION_FLOOR = 'SPACE_ADD_LOCATION_FLOOR';
export const SPACE_ADD_LOCATION_FLOOR_SUCCESS =
  'SPACE_ADD_LOCATION_FLOOR_SUCCESS';
export const SPACE_ADD_LOCATION_FLOOR_ERROR = 'SPACE_ADD_LOCATION_FLOOR_ERROR';

// ------- MEETING ROOM -----
// GET
export const SPACE_GET_MEETING_LIST = 'SPACE_GET_MEETING_LIST';
export const SPACE_GET_MEETING_LIST_SUCCESS = 'SPACE_GET_MEETING_LIST_SUCCESS';
export const SPACE_GET_MEETING_LIST_ERROR = 'SPACE_GET_MEETING_LIST_ERROR';

// ADD
export const SPACE_ADD_MEETING = 'SPACE_ADD_MEETING';
export const SPACE_ADD_MEETING_SUCCESS = 'SPACE_ADD_MEETING_SUCCESS';
export const SPACE_ADD_MEETING_ERROR = 'SPACE_ADD_MEETING_ERROR';

/*----------------------------- CLIENT -----------------------------*/

// ------- BOOKING -----
// GET
export const CLIENT_GET_BOOKING_LIST = 'CLIENT_GET_BOOKING_LIST';
export const CLIENT_GET_BOOKING_LIST_SUCCESS =
  'CLIENT_GET_BOOKING_LIST_SUCCESS';
export const CLIENT_GET_BOOKING_LIST_ERROR = 'CLIENT_GET_BOOKING_LIST_ERROR';

// ADD
export const CLIENT_ADD_BOOKING = 'CLIENT_ADD_BOOKING';
export const CLIENT_ADD_BOOKING_SUCCESS = 'CLIENT_ADD_BOOKING_SUCCESS';
export const CLIENT_ADD_BOOKING_ERROR = 'CLIENT_ADD_BOOKING_ERROR';

// ------- CUSTOMER -----
// GET
export const CLIENT_GET_CUSTOMER_LIST = 'CLIENT_GET_CUSTOMER_LIST';
export const CLIENT_GET_CUSTOMER_LIST_SUCCESS =
  'CLIENT_GET_CUSTOMER_LIST_SUCCESS';
export const CLIENT_GET_CUSTOMER_LIST_ERROR = 'CLIENT_GET_CUSTOMER_LIST_ERROR';

// ADD
export const CLIENT_ADD_CUSTOMER = 'CLIENT_ADD_CUSTOMER';
export const CLIENT_ADD_CUSTOMER_SUCCESS = 'CLIENT_ADD_CUSTOMER_SUCCESS';
export const CLIENT_ADD_CUSTOMER_ERROR = 'CLIENT_ADD_CUSTOMER_ERROR';

export * from './menu/actions';
export * from './settings/actions';
export * from './auth/actions';
export * from './dashboard/actions';
export * from './space/actions';
export * from './client/actions';
